# Generated by Django 4.2.4 on 2023-08-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_contactmodel_created_alter_studentmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='interested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
